# to create this environment, run conda env create -f requirements.yml
name: raffle
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - et_xmlfile=1.1.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openpyxl=3.1.5
  - openssl=3.0.15
  - pandas=2.2.2
  - pip=24.2
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
